### ISSUE TITLE
Use WinGet Releaser for automated releases to WinGet

### ISSUE THREAD

**Issue by russellbanks** [Echostorm44/RipShout#1]
Pull requests to winget-pkgs can be automated with [WinGet Releaser](https://github.com/vedantmgoyal2009/winget-releaser), a workflow that runs on release, generates a manifest and automatically creates a pull request.

It would look a bit like this:
```yaml
name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: FleetingClarityStudios.RipShout
          token: ${{ secrets.WINGET_TOKEN }}
```

I'd be happy to create a pull request to add this, if you would like.
